# Generated by Django 5.0.4 on 2024-04-20 05:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=32)),
                ('website', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.industrysector')),
            ],
        ),
        migrations.CreateModel(
            name='FootprintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(choices=[('MONTH', 'Month'), ('YEAR', 'Year')], max_length=10)),
                ('total_emission', models.FloatField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 4, 20, 5, 44, 53, 765833))),
                ('transaction_id', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.company')),
            ],
        ),
        migrations.CreateModel(
            name='FootprintBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope1_emission', models.FloatField()),
                ('scope2_emission', models.FloatField()),
                ('scope3_emission', models.FloatField()),
                ('footprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.footprintreport')),
            ],
        ),
        migrations.CreateModel(
            name='FootprintSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('emissions', models.FloatField()),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.footprintbreakdown')),
            ],
        ),
        migrations.CreateModel(
            name='GreenInitiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_area', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.company')),
            ],
        ),
    ]
