# Generated by Django 5.0.4 on 2024-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_footprintreport_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='wallet_address',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
