# Generated by Django 5.0.4 on 2024-04-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_company_wallet_address_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
