# Generated by Django 5.0.4 on 2024-04-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_transaction_id_footprintreport_transaction_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprintreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
