# Generated by Django 5.0.4 on 2024-04-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_footprintreport_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprintbreakdown',
            name='footprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.footprintreport'),
        ),
    ]
